[workspace]
resolver = "2"
members = [
    "crates/tensorcontract",
    "crates/tensorcontract-tapp",
    "crates/tensorcontract-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.89"   # AVX-512 intrinsics + std feature detection stabilised here
license = "MIT OR Apache-2.0"
repository = "https://github.com/lkdvos/tensorcontract-rs"
authors = ["Lukas Devos <ldevos@flatironinstitute.org>"]

[workspace.dependencies]
num-complex = { version = "0.4", default-features = false, features = ["std"] }
tensorcontract = { path = "crates/tensorcontract", version = "0.1.0" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = 1

[profile.bench]
inherits = "release"
