//! The five-loop driver.
//!
//! Structurally identical to BLIS's GEMM: two levels of cache blocking with a
//! packing step at each, wrapped around a register-blocked micro-kernel. The
//! only tensor-specific part is that every matrix access goes through a
//! scatter vector.
//!
//! ```text
//! for each Hadamard (batch) index h          -- offsets all four operands
//!   loop 5: for jc in 0..N step NC
//!     loop 4: for pc in 0..K step KC
//!               pack B[pc:pc+KC, jc:jc+NC] -> Bp    (NR slivers)
//!       loop 3: for ic in 0..M step MC
//!                 pack A[ic:ic+MC, pc:pc+KC] -> Ap  (MR slivers)
//!         loop 2: for jr in 0..NC step NR
//!           loop 1: for ir in 0..MC step MR
//!                     micro-kernel -> MR x NR tile
//!                     write back to C/D through the scatter vectors
//! ```
//!
//! The loop nest is identical for real and for all three complex methods. What
//! the complex method changes is captured entirely by the selected
//! [`Ukr`](crate::kernel::Ukr): its `a_pack`/`b_pack` formats, its per-k sliver
//! widths, its tile size and its `tile_fmt`. Nothing here branches on the
//! method, which is what makes the three genuinely comparable — they share
//! every line of index analysis, packing traversal, loop arithmetic and
//! write-back scatter.
//!
//! `beta` and the `C` operand are consumed on the first `pc` iteration only;
//! later iterations accumulate into `D`.

use crate::buffer::Panel;
use crate::element::Element;
use crate::kernel::{config_for, Blocking, KernelSet};
use crate::pack::{pack_panel, panel_len};
use crate::plan::Plan;
use crate::scatter::build_block_scatter;
use crate::writeback::{scale_only, writeback};

/// Execute a plan.
///
/// # Safety
/// * `a`, `b`, `d` must be valid for all offsets generated by the plan's
///   scatter vectors (reads for `a`/`b`, reads and writes for `d`).
/// * `c` must likewise be valid for reads unless `beta` is zero, in which case
///   it is never dereferenced and may be dangling.
/// * `d` must not alias `a` or `b`.
pub unsafe fn execute<T>(
    plan: &Plan,
    alpha: T,
    a: *const T,
    b: *const T,
    beta: T,
    c: *const T,
    d: *mut T,
) where
    T: Element,
    T::Real: KernelSet,
{
    if plan.is_empty() {
        return;
    }

    let cfg = config_for::<T>(plan.complex_method());
    let cfg = match plan.blocking {
        Some(blk) => cfg.with_blocking(blk),
        None => cfg,
    };
    let ukr = cfg.ukr;
    let (mr, nr) = (ukr.mr, ukr.nr);

    let m = plan.stats.m;
    let n = plan.stats.n;
    let k = plan.stats.k;

    // Empty contraction dimension: D = op_D(beta * op_C(C)).
    if plan.has_empty_contraction() {
        for h in 0..plan.stats.batch {
            scale_only::<T>(
                beta,
                c.offset(plan.h_c[h] as isize),
                &plan.c_m,
                &plan.c_n,
                plan.conj_c,
                d.offset(plan.h_d[h] as isize),
                &plan.d_m,
                &plan.d_n,
                plan.conj_d,
            );
        }
        return;
    }

    let Blocking { mc, kc, nc } = cfg.blk;
    let mc = mc.min(m.next_multiple_of(mr));
    let nc = nc.min(n.next_multiple_of(nr));

    // Block-scatter metadata. Cheap (O(M/MR + N/NR)) and element-type
    // dependent only through MR/NR, so it lives here rather than in the plan.
    let a_m_bs = build_block_scatter(&plan.a_m, mr);
    let b_n_bs = build_block_scatter(&plan.b_n, nr);

    // Panel sizes come from the kernel's declared per-k sliver widths, so a
    // method that packs more reals per element (1m's "1e", 3m's sum plane)
    // automatically gets a correspondingly larger buffer.
    let mut ap = Panel::<T::Real>::new(panel_len(mc, mr, kc, ukr.a_pack));
    let mut bp = Panel::<T::Real>::new(panel_len(nc, nr, kc, ukr.b_pack));
    let mut tile = Panel::<T::Real>::new(ukr.tile);
    let ap_ptr = ap.as_mut_ptr();
    let bp_ptr = bp.as_mut_ptr();
    let tile_ptr = tile.as_mut_ptr();

    let one = T::one();

    for h in 0..plan.stats.batch {
        let ah = a.offset(plan.h_a[h] as isize);
        let bh = b.offset(plan.h_b[h] as isize);
        let ch = c.offset(plan.h_c[h] as isize);
        let dh = d.offset(plan.h_d[h] as isize);

        // ---- loop 5: N blocking -------------------------------------------
        let mut jc = 0;
        while jc < n {
            let jc_len = nc.min(n - jc);

            // ---- loop 4: K blocking ---------------------------------------
            let mut pc = 0;
            while pc < k {
                let pc_len = kc.min(k - pc);
                let first_k_block = pc == 0;

                pack_panel::<T>(
                    bh,
                    &plan.b_n[jc..jc + jc_len],
                    &b_n_bs[jc / nr..(jc + jc_len).div_ceil(nr)],
                    &plan.b_k[pc..pc + pc_len],
                    nr,
                    plan.conj_b,
                    ukr.b_pack,
                    bp_ptr,
                );
                let b_sliver = ukr.b_per_k * pc_len;

                // ---- loop 3: M blocking -----------------------------------
                let mut ic = 0;
                while ic < m {
                    let ic_len = mc.min(m - ic);

                    pack_panel::<T>(
                        ah,
                        &plan.a_m[ic..ic + ic_len],
                        &a_m_bs[ic / mr..(ic + ic_len).div_ceil(mr)],
                        &plan.a_k[pc..pc + pc_len],
                        mr,
                        plan.conj_a,
                        ukr.a_pack,
                        ap_ptr,
                    );
                    let a_sliver = ukr.a_per_k * pc_len;

                    // ---- loop 2: NR ---------------------------------------
                    let mut jr = 0;
                    while jr < jc_len {
                        let nrem = nr.min(jc_len - jr);
                        let j0 = jc + jr;
                        let bpan = bp_ptr.add((jr / nr) * b_sliver);

                        // ---- loop 1: MR -----------------------------------
                        let mut ir = 0;
                        while ir < ic_len {
                            let mrem = mr.min(ic_len - ir);
                            let i0 = ic + ir;
                            let apan = ap_ptr.add((ir / mr) * a_sliver);

                            (ukr.func)(pc_len, apan, bpan, tile_ptr);

                            if first_k_block {
                                writeback::<T>(
                                    tile_ptr,
                                    ukr.tile_fmt,
                                    mr,
                                    nr,
                                    mrem,
                                    nrem,
                                    alpha,
                                    beta,
                                    ch,
                                    &plan.c_m[i0..i0 + mrem],
                                    &plan.c_n[j0..j0 + nrem],
                                    plan.conj_c,
                                    dh,
                                    &plan.d_m[i0..i0 + mrem],
                                    &plan.d_n[j0..j0 + nrem],
                                    plan.conj_d,
                                );
                            } else {
                                // Accumulate: C := D, beta := 1, and conjugate
                                // the readback exactly when op_D conjugates.
                                writeback::<T>(
                                    tile_ptr,
                                    ukr.tile_fmt,
                                    mr,
                                    nr,
                                    mrem,
                                    nrem,
                                    alpha,
                                    one,
                                    dh as *const T,
                                    &plan.d_m[i0..i0 + mrem],
                                    &plan.d_n[j0..j0 + nrem],
                                    plan.conj_d,
                                    dh,
                                    &plan.d_m[i0..i0 + mrem],
                                    &plan.d_n[j0..j0 + nrem],
                                    plan.conj_d,
                                );
                            }
                            ir += mr;
                        }
                        jr += nr;
                    }
                    ic += mc;
                }
                pc += kc;
            }
            jc += nc;
        }
    }
}
